"""
Generates a downloadable PDF report ("certificate") for a single scan
result, using reportlab - the standard Python library for programmatic PDF
creation (distinct from pypdf, which only reads/manipulates existing PDFs).

Works directly from the same scan-result shape already used for history
(GET /scans/{id}), so one function serves both a freshly-computed result
and any past scan.
"""
import io
from datetime import datetime
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)

VERDICT_COLORS = {
    "low": colors.HexColor("#2f6e4e"),
    "medium": colors.HexColor("#93701c"),
    "high": colors.HexColor("#a63b2e"),
}
LINE_COLOR = colors.HexColor("#dcd7c9")
MUTED_COLOR = colors.HexColor("#5b6472")

MEDIA_LABELS = {
    "text": "Text",
    "image": "Image",
    "video": "Video",
    "pdf": "PDF",
    "similarity": "Document comparison",
}

MAX_TEXT_PREVIEW_CHARS = 3000
MAX_LISTED_ITEMS = 10


def _safe(value) -> str:
    """Escapes text for reportlab's mini-XML markup, so content containing
    '<', '>', or '&' (quite possible in scanned text) doesn't break rendering."""
    return escape(str(value))


def _styles():
    # IMPORTANT: reportlab's ParagraphStyle defaults `leading` (line height)
    # to a flat 12pt regardless of fontSize unless set explicitly - it does
    # NOT auto-scale with font size. Every style below sets it explicitly
    # at roughly 1.2-1.3x the font size; omitting it is what caused the
    # verdict percentage to overlap the line beneath it.
    styles = getSampleStyleSheet()
    styles.add(
        ParagraphStyle(
            name="ReportTitle", fontSize=20, leading=24, spaceAfter=4, fontName="Helvetica-Bold"
        )
    )
    styles.add(
        ParagraphStyle(
            name="ReportSubtitle", fontSize=10, leading=14, textColor=MUTED_COLOR, spaceAfter=18
        )
    )
    styles.add(
        ParagraphStyle(
            name="SectionHeading",
            fontSize=13,
            leading=17,
            spaceBefore=16,
            spaceAfter=8,
            fontName="Helvetica-Bold",
        )
    )
    styles.add(ParagraphStyle(name="BodySmall", fontSize=9.5, leading=14, alignment=TA_LEFT))
    return styles


def _rule(color=LINE_COLOR):
    return HRFlowable(width="100%", color=color, thickness=1, spaceAfter=8)


def generate_report_pdf(scan: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
    )
    styles = _styles()
    story = []

    media_type = scan.get("media_type", "text")
    is_similarity = media_type == "similarity"

    story.append(Paragraph("Is it AI? — Scan Report", styles["ReportTitle"]))
    generated_at = datetime.utcnow().strftime("%B %d, %Y at %H:%M UTC")
    story.append(Paragraph(f"Generated {generated_at}", styles["ReportSubtitle"]))
    story.append(_rule())
    story.append(Spacer(1, 10))

    summary_rows = [
        ["Type", MEDIA_LABELS.get(media_type, media_type.title())],
        ["Item", _safe(scan.get("label", "—"))],
    ]
    created_at = scan.get("created_at")
    if created_at:
        summary_rows.append(["Scanned", created_at[:19].replace("T", " ") + " UTC"])

    summary_table = Table(summary_rows, colWidths=[1.3 * inch, 4.7 * inch])
    summary_table.setStyle(
        TableStyle(
            [
                ("FONTSIZE", (0, 0), (-1, -1), 9.5),
                ("TEXTCOLOR", (0, 0), (0, -1), MUTED_COLOR),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(summary_table)
    story.append(Spacer(1, 14))

    if is_similarity:
        _add_similarity_sections(story, styles, scan)
    else:
        _add_detection_sections(story, styles, scan)

    story.append(Spacer(1, 20))
    story.append(_rule())
    story.append(
        Paragraph(
            "This report is a probability/similarity estimate from automated signals, "
            "not a determination of fact. Generated by Is it AI? — a university "
            "project, not intended for high-stakes decisions.",
            styles["BodySmall"],
        )
    )

    doc.build(story)
    return buffer.getvalue()


def _verdict_style(styles, key: str) -> ParagraphStyle:
    return ParagraphStyle(
        "Verdict",
        parent=styles["Normal"],
        fontSize=26,
        leading=32,  # explicit - see note in _styles(); this was the actual overlap bug
        spaceAfter=8,
        fontName="Helvetica-Bold",
        textColor=VERDICT_COLORS.get(key, MUTED_COLOR),
    )


def _add_detection_sections(story, styles, scan):
    percent = round((scan.get("ai_probability") or 0) * 100)
    confidence = scan.get("confidence", "low")

    story.append(Paragraph(f"{percent}% AI-probability", _verdict_style(styles, confidence)))
    story.append(Paragraph(f"Confidence: {_safe(confidence)}", styles["BodySmall"]))
    story.append(Spacer(1, 10))

    components = scan.get("components") or {}
    if components:
        story.append(Paragraph("Signal breakdown", styles["SectionHeading"]))
        rows = [[_safe(k.replace("_", " ").title()), _safe(v)] for k, v in components.items()]
        table = Table(rows, colWidths=[2.5 * inch, 3.5 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("GRID", (0, 0), (-1, -1), 0.5, LINE_COLOR),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )
        story.append(table)
        story.append(Spacer(1, 10))

    risk_flags = scan.get("risk_flags") or []
    if risk_flags:
        story.append(Paragraph("What stood out", styles["SectionHeading"]))
        for flag in risk_flags:
            story.append(Paragraph(f"• {_safe(flag.replace('_', ' '))}", styles["BodySmall"]))
        story.append(Spacer(1, 10))

    sentences = scan.get("sentences")
    extracted_text = scan.get("extracted_text")
    if sentences:
        story.append(Paragraph("Sentence-level view", styles["SectionHeading"]))
        for s in sentences:
            marker = " [flagged]" if (s.get("ai_probability") or 0) >= 0.6 else ""
            story.append(Paragraph(f"{_safe(s.get('text', ''))}{marker}", styles["BodySmall"]))
            story.append(Spacer(1, 2))
    elif extracted_text:
        story.append(Paragraph("Text that was scored", styles["SectionHeading"]))
        preview = extracted_text[:MAX_TEXT_PREVIEW_CHARS]
        story.append(Paragraph(_safe(preview).replace("\n", "<br/>"), styles["BodySmall"]))
        if len(extracted_text) > MAX_TEXT_PREVIEW_CHARS:
            story.append(Paragraph("… (truncated for this report)", styles["BodySmall"]))


def _add_similarity_sections(story, styles, scan):
    components = scan.get("components") or {}
    percent = round((scan.get("ai_probability") or 0) * 100)  # similarity_score stored here
    verdict = scan.get("confidence", "low")  # verdict stored here

    doc_a = components.get("document_a_label", "Document A")
    doc_b = components.get("document_b_label", "Document B")

    story.append(Paragraph(f"{percent}% wording overlap", _verdict_style(styles, verdict)))
    story.append(
        Paragraph(
            f'Comparing <b>{_safe(doc_a)}</b> and <b>{_safe(doc_b)}</b>',
            styles["ReportSubtitle"],
        )
    )

    semantic_score = components.get("semantic_overlap_score")
    if semantic_score is not None:
        story.append(
            Paragraph(
                f"Paraphrase overlap: {round(semantic_score * 100)}% of sentences matched",
                styles["BodySmall"],
            )
        )
    story.append(Spacer(1, 12))

    passages = components.get("matching_passages") or []
    if passages:
        story.append(Paragraph("Matching passages (shared wording)", styles["SectionHeading"]))
        for p in passages[:MAX_LISTED_ITEMS]:
            story.append(Paragraph(f"\u201c{_safe(p.get('text', ''))}\u201d", styles["BodySmall"]))
            story.append(Spacer(1, 4))

    paraphrase_matches = components.get("paraphrase_matches") or []
    if paraphrase_matches:
        story.append(Paragraph("Possible paraphrased passages", styles["SectionHeading"]))
        for m in paraphrase_matches[:MAX_LISTED_ITEMS]:
            story.append(
                Paragraph(f"A: \u201c{_safe(m.get('sentence_a', ''))}\u201d", styles["BodySmall"])
            )
            story.append(
                Paragraph(f"B: \u201c{_safe(m.get('sentence_b', ''))}\u201d", styles["BodySmall"])
            )
            story.append(Spacer(1, 8))
